apiVersion: v1
kind: ConfigMap
metadata:
  name: devpod-dashboard-config
  namespace: devpod
  labels:
    app: devpod-dashboard
data:
  DASHBOARD_PORT: "3000"
  DASHBOARD_NAMESPACE: "devpod"
  DASHBOARD_DEFAULT_IMAGE: "mcr.microsoft.com/devcontainers/base:ubuntu"
  OPENVSCODE_PATH: "/opt/openvscode-server"
  DASHBOARD_DISK_SIZE: "50Gi"
  DASHBOARD_USERS_FILE: ""
  # SESSION_SECRET: "generate-with-openssl-rand-base64-32"
  NODE_TLS_REJECT_UNAUTHORIZED: "0"
