apiVersion: v1
kind: Service
metadata:
  name: devpod-dashboard
  namespace: devpod
  labels:
    app: devpod-dashboard
spec:
  type: NodePort
  selector:
    app: devpod-dashboard
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
      protocol: TCP
